routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Obspackage\Validpackage\Validpackage;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('purchaseOrder', 'PurchaseOrderController');

Route::get('/validpackage/{name}', function($sName) {
    $oGreetr = new Validpackage();
    return $oGreetr->greet($sName);
});

Route::get('/emailvalidate',function() {
return view('emailvalidate');
});

Route::post('emailvalidation/validateemail','EmailvalidationController@validateemail');

app/PurchaseOrder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PurchaseOrder extends Model
{
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'mobile',
        'items_purchased',
        'total',
        'gst',
        'amount', 
        'created_at',
        'updated_at',     
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmailvalidationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Obs\Validpackage\Validpackage;

class EmailvalidationController extends Controller
{
    public function validateemail(Request $name) {
    	$oGreetr = new Validpackage();
        return $oGreetr->greet($sName);
});
    }
}

app/Http/Controllers/PurchaseOrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
 use Illuminate\Support\Facades\Input;
use App\PurchaseOrder;
use Obspackage\Validpackage\Validpackage;


class PurchaseOrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $purchaseOrders = PurchaseOrder::all();

        return view('purchaseOrder.index', compact('purchaseOrders'));
    }


    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
        return view('purchaseOrder.create');
    }


public function store(Request $request) {

    $validation = new Validpackage();
        $message = $validation->emailvalidate($request->email);
        return redirect('/purchaseOrder/create')
            ->with('message',$message);
}
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storecopy(Request $request)
    {
       $rules = array(
            'first_name'=>'required',
            'last_name'=>'required',
            'email'=>'required|email',
            'mobile'=>'required|digits:10',
            'items_purchased'=>'required|integer',
            'total'=>'required|integer',
            'gst'=>'required|integer',
            'amount'=>'required|integer',
        );
$validator = Validator::make($request->all(), $rules);
 if ($validator->fails()) {

        // get the error messages from the validator
        $messages = $validator->messages();

        // redirect our user back to the form with the errors from the validator
        return redirect('/purchaseOrder/create')
            ->withErrors($validator)->withInput($request->input());

    } else {
        // validation successful ---------------------------

        // our duck has passed all tests!
        // let him enter the database

        // create the data for our duck
       $purchaseOrder = new PurchaseOrder([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'email' => $request->get('email'),
            'mobile' => $request->get('mobile'),
            'items_purchased' => $request->get('items_purchased'),
            'total' => $request->get('total'),
            'gst' => $request->get('gst'),
            'amount' => $request->get('amount')
        ]);
$purchaseOrder->save();
        // redirect ----------------------------------------
        // redirect our user back to the form so they can do it all over again
        return redirect('/purchaseOrder')->with('success', 'Purchase Order saved!');

    }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $purchaseOrders = PurchaseOrder::find($id);
        return view('purchaseOrder.edit', compact('purchaseOrders'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      // echo "hi"; exit;
       $rules = array(
            'first_name'=>'required',
            'last_name'=>'required',
            'email'=>'required|email',
            'mobile'=>'required|digits:10',
            'items_purchased'=>'required|integer',
            'total'=>'required|integer',
            'gst'=>'required|integer',
            'amount'=>'required|integer',
        );
$validator = Validator::make($request->all(), $rules);
 if ($validator->fails()) {

        // get the error messages from the validator
        $messages = $validator->messages();

        // redirect our user back to the form with the errors from the validator
        return redirect('/purchaseOrder/'.$id.'/edit/')
            ->withErrors($validator)->withInput($request->input());

    } else {
        // validation successful ---------------------------

        // our duck has passed all tests!
        // let him enter the database
 $purchaseOrder = PurchaseOrder::find($id);
  $purchaseOrder->first_name =  $request->get('first_name');
  $purchaseOrder->last_name =  $request->get('last_name');
  $purchaseOrder->email =  $request->get('email');
  $purchaseOrder->mobile =  $request->get('mobile');
  $purchaseOrder->items_purchased =  $request->get('items_purchased');
  $purchaseOrder->total =  $request->get('total');
  $purchaseOrder->gst =  $request->get('gst');
  $purchaseOrder->amount =  $request->get('amount');
       
       
$purchaseOrder->save();
        // redirect ----------------------------------------
        // redirect our user back to the form so they can do it all over again
        return redirect('/purchaseOrder')->with('success', 'Purchase Order updated!');

    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $purchaseOrder = PurchaseOrder::find($id);
        $purchaseOrder->delete();

        return redirect('/purchaseOrder')->with('success', 'Purchase Order deleted!');
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Laravel NewBie</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/createcopy.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a Purchase Order</h1>
  <div>
    
      <form method="post" action="{{ route('purchaseOrder.store') }}">

          @csrf
          <div class="form-group">    
              <label for="first_name">First Name:</label>
              <input type="text" class="form-control" name="first_name" value="{{ old('first_name') }}"/>
              @if ($errors->has('first_name')) <p class="help-block">{{ $errors->first('first_name') }}</p> @endif
          </div>

          <div class="form-group">
              <label for="last_name">Last Name:</label>
              <input type="text" class="form-control" name="last_name" value="{{ old('last_name') }}"/>
              @if ($errors->has('last_name')) <p class="help-block">{{ $errors->first('last_name') }}</p> @endif
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email" value="{{ old('email') }}"/>
              @if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="city">Mobile:</label>
              <input type="text" class="form-control" name="mobile" value="{{ old('mobile') }}"/>
              @if ($errors->has('mobile')) <p class="help-block">{{ $errors->first('mobile') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="country">No.Of Items Purchased:</label>
              <input type="text" class="form-control" name="items_purchased" value="{{ old('items_purchased') }}"/>
              @if ($errors->has('items_purchased')) <p class="help-block">{{ $errors->first('items_purchased') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="country">Total:</label>
              <input type="text" class="form-control" name="total" value="{{ old('total') }}"/>
              @if ($errors->has('total')) <p class="help-block">{{ $errors->first('total') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="job_title">GST:</label>
              <input type="text" class="form-control" name="gst" value="{{ old('gst') }}"/>
              @if ($errors->has('gst')) <p class="help-block">{{ $errors->first('gst') }}</p> @endif
          </div>         
          <div class="form-group">
              <label for="job_title">Amount:</label>
              <input type="text" class="form-control" name="amount" value="{{ old('amount') }}"/>
              @if ($errors->has('amount')) <p class="help-block">{{ $errors->first('amount') }}</p> @endif
          </div>                     
          <button type="submit" class="btn btn-primary-outline">Add Purchase Order</button>
          <a href="{{ route('purchaseOrder.index')}}" class="btn btn-primary">Cancel</a>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/emailvalidate.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Email Validation</h1>
  <div>
    <form method="post" action="{{ route('emailvalidation.validateemail') }}">

          @csrf
          <div class="form-group">    
              <label for="first_name">Email Address:</label>
              <input type="text" class="form-control" name="email" /> 
          </div>
           <button type="submit" class="btn btn-primary-outline">Validate</button>
        </form>
     
  </div>
</div>
</div>
@endsection

resources/views/purchaseOrder/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Email Validation</h1>
  <div>
     @if (session('message'))
    <div class="col-sm-12">
        <div class="alert @if (session('message.true') == 1) alert-success else alert-error @endif">
            {{ session('message.success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                   
                </button>
        </div>
    </div>
@endif
    <form method="post" action="{{ route('purchaseOrder.store') }}">

          @csrf
          <div class="form-group">    
              <label for="first_name">Email Address:</label>
              <input type="email" required class="form-control" name="email" value="@if (session('message')) {{session('message.email')}} @endif" /> 
          </div>
           <button type="submit" class="btn btn-primary-outline">Validate</button>
        </form>
     
  </div>
</div>
</div>
@endsection

resources/views/purchaseOrder/edit.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Update Purchase Order</h1>
  <div>
    
      <form method="post" action="{{ route('purchaseOrder.update', $purchaseOrders->id) }}">">
          @method('PATCH') 
          @csrf
          <div class="form-group">    
              <label for="first_name">First Name:</label>
              <input type="text" class="form-control" name="first_name" value="{{ $purchaseOrders->first_name}}"/>
              @if ($errors->has('first_name')) <p class="help-block">{{ $errors->first('first_name') }}</p> @endif
          </div>

          <div class="form-group">
              <label for="last_name">Last Name:</label>
              <input type="text" class="form-control" name="last_name" value="{{ $purchaseOrders->last_name }}"/>
              @if ($errors->has('last_name')) <p class="help-block">{{ $errors->first('last_name') }}</p> @endif
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email" value="{{ $purchaseOrders->email }}"/>
              @if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="city">Mobile:</label>
              <input type="text" class="form-control" name="mobile" value="{{ $purchaseOrders->mobile }}"/>
              @if ($errors->has('mobile')) <p class="help-block">{{ $errors->first('mobile') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="country">No.Of Items Purchased:</label>
              <input type="text" class="form-control" name="items_purchased" value="{{$purchaseOrders->items_purchased }}"/>
              @if ($errors->has('items_purchased')) <p class="help-block">{{ $errors->first('items_purchased') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="country">Total:</label>
              <input type="text" class="form-control" name="total" value="{{ $purchaseOrders->total }}"/>
              @if ($errors->has('total')) <p class="help-block">{{ $errors->first('total') }}</p> @endif
          </div>
          <div class="form-group">
              <label for="job_title">GST:</label>
              <input type="text" class="form-control" name="gst" value="{{ $purchaseOrders->gst }}"/>
              @if ($errors->has('gst')) <p class="help-block">{{ $errors->first('gst') }}</p> @endif
          </div>         
          <div class="form-group">
              <label for="job_title">Amount:</label>
              <input type="text" class="form-control" name="amount" value="{{ $purchaseOrders->amount }}"/>
              @if ($errors->has('amount')) <p class="help-block">{{ $errors->first('amount') }}</p> @endif
          </div>                     
          <button type="submit" class="btn btn-primary-outline">Update Purchase Order</button>
          <a href="{{ route('purchaseOrder.index')}}" class="btn btn-primary">Cancel</a>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/purchaseOrder/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Purchase Order</h1>    
    @if (session('success'))
    <div class="col-sm-12">
        <div class="alert  alert-success alert-dismissible">
            {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                   
                </button>
        </div>
    </div>
@endif
     <a href="{{ route('purchaseOrder.create')}}" class="btn btn-primary">Create</a>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Email</td>
          <td>Mobile</td>
          <td>No.Of Items purchased</td>
          <td>Total</td>
          <td>GST</td>
          <td>Amount</td>
          <td colspan = 4>Actions</td>
        </tr>
    </thead>
    <tbody>
      
        @foreach($purchaseOrders as $purchaseOrder)
        <tr>
            <td>{{ 1 }}</td>
            <td>{{$purchaseOrder->first_name}} {{$purchaseOrder->last_name}}</td>
            <td>{{$purchaseOrder->email}}</td>
            <td>{{$purchaseOrder->mobile}}</td>
            <td>{{$purchaseOrder->items_purchased}}</td>
            <td>{{$purchaseOrder->total}}</td>
            <td>{{$purchaseOrder->gst}}</td>
            <td>{{$purchaseOrder->amount}}</td>
            <td>
                <a href="{{ route('purchaseOrder.edit',$purchaseOrder->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('purchaseOrder.destroy', $purchaseOrder->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
@endsection